import Head from "next/head";
import "./styles.css";
import FirstSection from "./FirstSection";
import SecondSection from "./SecondSection";
import Slider from "./Slider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Slider />
        <FirstSection />
        <div className="bg-lightGray py-2">
          <SecondSection />
        </div>
      </main>
    </>
  );
}
