import Head from "next/head";
import FirstSection from "../components/home/FirstSection";
import SecondSection from "../components/home/SecondSection";
import Slider from "../components/home/Slider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="../styles/output.css" rel="stylesheet"></link> */}
      </Head>

      <main>
        <Slider />
        <FirstSection />
        <div className="bg-lightGray py-2">
          <SecondSection />
        </div>
      </main>
    </>
  );
}
